#!/bin/sh
#
# "$Id$"
#
# makesrcdist - make a source distribution of EPM.
#

if test $# = 0; then
	echo Updating for snapshot...
	svn up
	rev=`svnversion . | sed -e '1,$s/[a-zA-Z]//g'`
	version="4.0svn"
	revision="-r$rev"
	fileversion="4.0svn-r$rev"
	url="."
else
	echo Creating tag for release...
	rev="1"
	version=$1
	revision=""
	fileversion=$1
	url="https://svn.easysw.com/public/epm/tags/release-$version"

	svn copy https://svn.easysw.com/public/epm/branches/branch-4 "$url" \
		-m "Tag $version" || exit 1
fi

echo Exporting $fileversion...
rm -rf /tmp/epm-$version
svn export $url /tmp/epm-$version

echo Cleaning source directory...
cd /tmp/epm-$version
rm -f makesrcdist
cd ..

echo -n Archiving...gz
tar czf epm-$fileversion-source.tar.gz epm-$version

echo -n ...bz2
tar cjf epm-$fileversion-source.tar.bz2 epm-$version
echo "..."

echo Removing temporary files...
rm -rf epm-$version

echo "Done!"

#
# End of "$Id$".
#
