#!/bin/sh
#
# makesrcdist - make a source distribution of EPM.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating epm-$version-source.tar.gz...
git archive --format tar --prefix=epm-$version/ HEAD | gzip -v9 >epm-$version.tar.gz
gpg --detach-sign epm-$version.tar.gz
