// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "setup.h"

static void cb_ESP(Fl_Window*, void*) {
  if (CancelButton->active())
  exit(0);
}

Fl_Wizard *Wizard=(Fl_Wizard *)0;

Fl_Group *WelcomePane=(Fl_Group *)0;

Fl_Box *WelcomeImage=(Fl_Box *)0;

Fl_Group *TypePane=(Fl_Group *)0;

Fl_Round_Button *TypeButton[8]={(Fl_Round_Button *)0};

Fl_Group *SoftwarePane=(Fl_Group *)0;

Fl_Check_Browser *SoftwareList=(Fl_Check_Browser *)0;

Fl_Box *SoftwareSize=(Fl_Box *)0;

Fl_Button *InstallAllButton=(Fl_Button *)0;

static void cb_InstallAllButton(Fl_Button*, void*) {
  SoftwareList->check_all();
list_cb(0,0);
}

Fl_Button *InstallNoneButton=(Fl_Button *)0;

static void cb_InstallNoneButton(Fl_Button*, void*) {
  SoftwareList->check_none();
list_cb(0,0);
}

Fl_Group *ConfirmPane=(Fl_Group *)0;

Fl_Browser *ConfirmList=(Fl_Browser *)0;

Fl_Group *LicensePane=(Fl_Group *)0;

Fl_Box *LicenseLabel=(Fl_Box *)0;

Fl_Browser *LicenseBrowser=(Fl_Browser *)0;

Fl_Round_Button *LicenseAccept=(Fl_Round_Button *)0;

static void cb_LicenseAccept(Fl_Round_Button*, void*) {
  NextButton->activate();
}

Fl_Round_Button *LicenseDecline=(Fl_Round_Button *)0;

static void cb_LicenseDecline(Fl_Round_Button*, void*) {
  NextButton->activate();
}

Fl_Group *InstallPane=(Fl_Group *)0;

Fl_Progress *InstallPercent=(Fl_Progress *)0;

Fl_Browser *InstallLog=(Fl_Browser *)0;

Fl_Button *PrevButton=(Fl_Button *)0;

static void cb_PrevButton(Fl_Button*, void*) {
  Wizard->prev();
}

Fl_Button *NextButton=(Fl_Button *)0;

Fl_Button *CancelButton=(Fl_Button *)0;

static void cb_CancelButton(Fl_Button*, void*) {
  exit(0);
}

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(580, 345, "ESP Software Installation Wizard");
    w = o;
    o->callback((Fl_Callback*)cb_ESP);
    { Fl_Wizard* o = Wizard = new Fl_Wizard(10, 10, 560, 290);
      { Fl_Group* o = WelcomePane = new Fl_Group(10, 10, 560, 280);
        o->hide();
        { Fl_Box* o = new Fl_Box(20, 20, 540, 25, "Welcome to the Software Installation Wizard");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = WelcomeImage = new Fl_Box(20, 50, 540, 180);
          o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(20, 235, 540, 55, "This wizard will install the software you select on your system.\n\nTo select\
 software for installation, please click on the \"Next\" button below.");
          o->align(133|FL_ALIGN_INSIDE);
        }
        o->end();
      }
      { Fl_Group* o = TypePane = new Fl_Group(10, 10, 555, 280);
        o->hide();
        { Fl_Box* o = new Fl_Box(20, 20, 540, 25, "Installation Type");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(20, 55, 540, 35, "Please select the type of software installation and click on the \"Next\" but\
ton below.");
          o->align(133|FL_ALIGN_INSIDE);
        }
        { Fl_Group* o = new Fl_Group(20, 100, 540, 185);
          { Fl_Round_Button* o = TypeButton[0] = new Fl_Round_Button(20, 100, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[1] = new Fl_Round_Button(20, 120, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[2] = new Fl_Round_Button(20, 140, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[3] = new Fl_Round_Button(20, 160, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[4] = new Fl_Round_Button(20, 180, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[5] = new Fl_Round_Button(20, 200, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[6] = new Fl_Round_Button(20, 220, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          { Fl_Round_Button* o = TypeButton[7] = new Fl_Round_Button(20, 240, 540, 20);
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)type_cb);
          }
          o->end();
        }
        o->end();
      }
      { Fl_Group* o = SoftwarePane = new Fl_Group(10, 10, 560, 290);
        o->hide();
        { Fl_Box* o = new Fl_Box(20, 20, 540, 25, "Software Selection");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(20, 55, 540, 35, "Please select the software you would like to install and click on the \"Next\
\" button below.");
          o->align(133|FL_ALIGN_INSIDE);
        }
        { Fl_Check_Browser* o = SoftwareList = new Fl_Check_Browser(20, 120, 540, 135, " Available Software:");
          o->type(3);
          o->box(FL_DOWN_BOX);
          o->selection_color(7);
          o->callback((Fl_Callback*)list_cb);
          o->align(FL_ALIGN_TOP_LEFT);
          o->when(3);
        }
        { Fl_Box* o = SoftwareSize = new Fl_Box(20, 265, 285, 25, "0k marked for installation.");
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Button* o = InstallAllButton = new Fl_Button(315, 265, 110, 25, "Install All");
          o->callback((Fl_Callback*)cb_InstallAllButton);
        }
        { Fl_Button* o = InstallNoneButton = new Fl_Button(435, 265, 125, 25, "Install None");
          o->callback((Fl_Callback*)cb_InstallNoneButton);
        }
        o->end();
      }
      { Fl_Group* o = ConfirmPane = new Fl_Group(10, 10, 560, 280);
        o->hide();
        { Fl_Box* o = new Fl_Box(20, 20, 540, 25, "Confirm Installation");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(20, 55, 540, 50, "You have selected the software below for installation. Click on the \"Next\" \
button to start the software installation or the \"Back\" button to change you\
r selections.");
          o->align(133|FL_ALIGN_INSIDE);
        }
        ConfirmList = new Fl_Browser(20, 110, 540, 180);
        o->end();
      }
      { Fl_Group* o = LicensePane = new Fl_Group(10, 10, 560, 280);
        o->hide();
        { Fl_Box* o = LicenseLabel = new Fl_Box(20, 20, 540, 40, "License Agreement for Some Product");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(133|FL_ALIGN_INSIDE);
        }
        { Fl_Browser* o = LicenseBrowser = new Fl_Browser(20, 65, 540, 175);
          o->textfont(4);
          o->textsize(12);
          Fl_Group::current()->resizable(o);
        }
        { Fl_Group* o = new Fl_Group(20, 245, 540, 45);
          { Fl_Round_Button* o = LicenseAccept = new Fl_Round_Button(20, 245, 540, 20, "Yes, I accept the terms and conditions of the software license agreement.");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)cb_LicenseAccept);
          }
          { Fl_Round_Button* o = LicenseDecline = new Fl_Round_Button(20, 270, 540, 20, "No, I do not accept the terms and conditions of the software license agreemen\
t.");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->callback((Fl_Callback*)cb_LicenseDecline);
          }
          o->end();
        }
        o->end();
      }
      { Fl_Group* o = InstallPane = new Fl_Group(10, 10, 560, 290);
        { Fl_Box* o = new Fl_Box(20, 20, 540, 25, "Installing Software...");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Progress* o = InstallPercent = new Fl_Progress(20, 75, 540, 15, "Progress Label...");
          o->selection_color(63);
          o->labelfont(2);
          o->align(FL_ALIGN_TOP_LEFT);
        }
        InstallLog = new Fl_Browser(20, 100, 540, 190);
        o->end();
      }
      o->end();
    }
    { Fl_Button* o = PrevButton = new Fl_Button(280, 310, 90, 25, "@-2< Back");
      o->callback((Fl_Callback*)cb_PrevButton);
    }
    { Fl_Button* o = NextButton = new Fl_Button(380, 310, 90, 25, "Next @-2>");
      o->callback((Fl_Callback*)next_cb);
    }
    { Fl_Button* o = CancelButton = new Fl_Button(480, 310, 90, 25, "Cancel");
      o->callback((Fl_Callback*)cb_CancelButton);
    }
    o->end();
  }
  return w;
}
