// generated by Fast Light User Interface Designer (fluid) version 1.00

#include "setup.h"

static Fl_Button *NextButton=(Fl_Button *)0;

static void cb_NextButton(Fl_Button*, void*) {
  Wizard->next();
NextButton->deactivate();
}

#include <FL/Fl_Bitmap.H>
static unsigned char bits_next[] =
"\0\0\0\0\0\0\0\0\0\0\0\0\f\2\0\0\4\0\24\2\0\b\f\0\24\2\0\b\34\0$\342\31\37<\
\0$2\23\t|\0""D\22\242\b\374\0""D\362""C\b\374\0\204\22@\b|\0\204\22\240\b<\0\
\4""3\23\t\34\0\4\343\31""3\f\0\0\0\0\0\4\0\0\0\0\0\0\0\0\0\0\0\0\0";
static Fl_Bitmap bitmap_next(bits_next, 42, 16);

static Fl_Button *CancelButton=(Fl_Button *)0;

static void cb_CancelButton(Fl_Button*, void*) {
  exit(0);
}

Fl_Wizard *Wizard=(Fl_Wizard *)0;

Fl_Group *WelcomePane=(Fl_Group *)0;

Fl_Group *SoftwarePane=(Fl_Group *)0;

Fl_Check_Browser *SoftwareList=(Fl_Check_Browser *)0;

static void cb_SoftwareList(Fl_Check_Browser*, void*) {
  if (SoftwareList->nchecked())
  NextButton->activate();
else
  NextButton->deactivate();
}

Fl_Group *InstallPane=(Fl_Group *)0;

Fl_Slider *InstallPercent=(Fl_Slider *)0;

Fl_Browser *InstallLog=(Fl_Browser *)0;

Fl_Window* make_window() {
  Fl_Window* w;
  { Fl_Window* o = new Fl_Window(450, 345, "ESP Software Wizard");
    w = o;
    { Fl_Button* o = NextButton = new Fl_Button(315, 310, 55, 25);
      bitmap_next.label(o);
      o->callback((Fl_Callback*)cb_NextButton);
    }
    { Fl_Button* o = CancelButton = new Fl_Button(380, 310, 60, 25, "Cancel");
      o->callback((Fl_Callback*)cb_CancelButton);
    }
    { Fl_Wizard* o = Wizard = new Fl_Wizard(0, 0, 450, 300);
      o->box(FL_THIN_UP_BOX);
      { Fl_Group* o = WelcomePane = new Fl_Group(10, 10, 430, 280);
        o->box(FL_FLAT_BOX);
        { Fl_Box* o = new Fl_Box(10, 10, 430, 25, "Welcome to Setup");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(40, 55, 370, 80, "This wizard will install the software you select on your system.\n\nTo select\
 software for installation, please click on the \"Next\" button below.");
          o->align(133|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(40, 150, 370, 140);
          o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
        }
        o->end();
      }
      { Fl_Group* o = SoftwarePane = new Fl_Group(10, 10, 430, 280);
        o->box(FL_FLAT_BOX);
        o->hide();
        { Fl_Box* o = new Fl_Box(10, 10, 430, 25, "Software Selection");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Box* o = new Fl_Box(40, 55, 370, 35, "Please select the software you would like to install and click on the \"Next\
\" button below.");
          o->align(133|FL_ALIGN_INSIDE);
        }
        { Fl_Check_Browser* o = SoftwareList = new Fl_Check_Browser(40, 120, 370, 170, " Available Software:");
          o->type(1);
          o->box(FL_DOWN_BOX);
          o->callback((Fl_Callback*)cb_SoftwareList);
          o->align(FL_ALIGN_TOP_LEFT);
          o->when(FL_WHEN_RELEASE);
        }
        o->end();
      }
      { Fl_Group* o = InstallPane = new Fl_Group(10, 10, 430, 280);
        o->box(FL_FLAT_BOX);
        o->hide();
        { Fl_Box* o = new Fl_Box(10, 10, 430, 25, "Installing Software...");
          o->labelfont(1);
          o->labelsize(18);
          o->labelcolor(4);
          o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
        }
        { Fl_Slider* o = InstallPercent = new Fl_Slider(40, 75, 365, 15, "Progress Label...");
          o->type(3);
          o->selection_color(63);
          o->labelfont(3);
          o->maximum(100);
          o->value(50);
          o->align(FL_ALIGN_TOP_LEFT);
        }
        InstallLog = new Fl_Browser(40, 100, 365, 180);
        o->end();
      }
      o->end();
    }
    o->end();
  }
  return w;
}
