// generated by Fast Light User Interface Designer (fluid) version 1.0104

#ifndef uninst_h
#define uninst_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "gui-common.h"
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *Wizard;
#include <FL/Fl_Group.H>
extern Fl_Group *WelcomePane;
#include <FL/Fl_Box.H>
extern Fl_Box *WelcomeImage;
extern Fl_Group *SoftwarePane;
#include <FL/Fl_Check_Browser.H>
extern void list_cb(Fl_Check_Browser*, void*);
extern Fl_Check_Browser *SoftwareList;
extern Fl_Box *SoftwareSize;
#include <FL/Fl_Button.H>
extern Fl_Button *RemoveAllButton;
extern Fl_Button *RemoveNoneButton;
extern Fl_Group *ConfirmPane;
#include <FL/Fl_Browser.H>
extern Fl_Browser *ConfirmList;
extern Fl_Group *RemovePane;
#include <FL/Fl_Progress.H>
extern Fl_Progress *RemovePercent;
extern Fl_Browser *RemoveLog;
extern Fl_Button *PrevButton;
extern void next_cb(Fl_Button*, void*);
extern Fl_Button *NextButton;
extern Fl_Button *CancelButton;
Fl_Window* make_window();
#endif
