.\"
.\" "$Id: epm.man,v 1.2 2001/06/20 18:34:57 mike Exp $"
.\"
.\"   Manual page for the ESP Package Manager (EPM).
.\"
.\"   Copyright 1999-2001 by Easy Software Products, all rights reserved.
.\"
.\"   This program is free software; you can redistribute it and/or modify
.\"   it under the terms of the GNU General Public License as published by
.\"   the Free Software Foundation; either version 2, or (at your option)
.\"   any later version.
.\"
.\"   This program is distributed in the hope that it will be useful,
.\"   but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"   GNU General Public License for more details.
.\"
.TH epm 1 "ESP Package Manager" "20 June 2001" "Easy Software Products"
.SH NAME
epm \- create software packages.
.SH SYNOPSIS
.B epm
[ \-f
.I format
] [ \-g ] [ \-k ] [ \-n[mrs] ] [ \-s
.I setup.xpm
] [ \--setup-image
.I setup.xpm
] [ \--setup-program
.I /foo/bar/setup
] [ \-v ] [
.I name=value
...
.I name=value
] product [
.I listfile
]
.SH DESCRIPTION
\fBepm\fR generates software packages complete with installation, removal, and
(if necessary) patch scripts. Unless otherwise specified, the files required
for \fIproduct\fR are read from a file named "\fIproduct\fR.list".
.LP
The \fI-f\fR option ("format") specifies the distribution format:
.TP 5
deb
.br
Generate a Debian distribution suitable for installation on a Debian Linux
system.
.TP 5
inst, tardist
.br
Generate an IRIX distribution suitable for installation on an system running
IRIX.
.TP 5
native
.br
Generate an native distribution. This uses \fIrpm\fR for Linux, \fIinst\fR for
IRIX, \fIpkg\fR for Solaris, and \fIswinstall\fR for HP-UX. All other
operating systems default to the \fIportable\fR format.
.TP 5
pkg
.br
Generate an AT&T software package. These are used primarily under Solaris.
.TP 5
portable
.br
Generate a portable distribution based on shell scripts and tar files.  The
resulting distribution is installed and removed the same way on all
operating systems. [default]
.TP 5
rpm
.br
Generate a Red Hat Package Manager ("RPM") distribution suitable
for installation on a Red Hat Linux system.
.TP 5
setld
.br
Generate a Tru64 (setld) software distribution.
.TP 5
swinstall, depot
.br
Generate a HP-UX software distribution.
.LP
Executable files in the distribution are normally stripped of debugging
information when packaged. To disable this functionality use the
\fI\-g\fR option.
.LP
Intermediate (spec, etc.) files used to create the distribution are normally
removed after the distribution is created. The \fI\-k\fR option keeps these
files in the distribution directory.
.LP
The \fI-s\fR and \fI--setup-image\fR options ("setup") include
the ESP Software Wizard with the specified XPM image file with
the distribution. This option is currently only supported by
portable distributions.
.LP
The \fI--setup-program\fR option specifies the setup executable
to use with the distribution. This option is currently only
supported by portable distributions.
.LP
The \fI-v\fR option ("verbose") increases the amount of information that is
reported. Use multiple v's for more verbose output.
.LP
Distributions normally are named
"product-version-system-release-machine.ext" and
"product-version-system-release-machine-patch.ext" (for patch
distributions.) The "system-release-machine" information can be
customized or eliminated using the \fI-n\fR option with the
appropriate trailing letters. Using \fI-n\fR by itself will
remove the "system-release-machine" string from the filename
entirely.
.LP
Debian, IRIX, portable, and Red Hat distributions use the extensions ".deb",
".tardist", "tar.gz", and ".rpm" respectively.
.SH LIST FILES
The EPM list file format is now described in the \fIepm.list(5)\fR
man page.
.SH ENVIRONMENT VARIABLES
The \fIRPMDIR\fR environment variable will override where EPM looks
for RPM distributions you generate. The default locations are
/usr/src/redhat/RPMS, /usr/src/RPM/RPMS, /usr/src/packages/RPMS,
and /usr/local/src/RPMS.
.SH KNOWN BUGS
EPM does not currently support generation of IRIX software patches.
.SH SEE ALSO
epminstall(1) - add a directory, file, or symlink to a list file.
mkepmlist(1) - make an epm list file from a directory.
epm.list(5) - epm list file format.
.SH COPYRIGHT
Copyright 1999-2001 by Easy Software Products, All Rights Reserved.
.LP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.\"
.\" End of "$Id: epm.man,v 1.2 2001/06/20 18:34:57 mike Exp $".
.\"
